title: VIPReply - AI Email Assistant
description: VIPReply helps you craft perfect email responses in seconds, saving you time and ensuring professional communication
baseurl: ""
url: ""

# Exclude from processing
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - README.md

include:
  - _pages
