title: VIPReply
description: VIPReply helps you craft perfect email responses in seconds, saving you time and ensuring professional communication
baseurl: ""
url: ""
app_url: "https://app.vipreply.ai"
encoding: UTF-8

# Exclude from processing
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - README.md

include:
  - _pages
